#!/bin/sh
set -e

if [ -n "${MAX_EXECUTION_TIME}" ]; then
    sed -i "s#.*max_execution_time.*#  \"max_execution_time\":${MAX_EXECUTION_TIME},#"  "${OCTANE_STATE_FILE}"
fi

/usr/local/bin/php -d variables_order=EGPCS /app/vendor/bin/swoole-server "${OCTANE_STATE_FILE}"

